### ISSUE TITLE
Develop SG specific palettes

### ISSUE THREAD

**Issue by lee-bunce** [DataScienceScotland/sgplot#2]
Do we want to develop alternative SG palette's that still meet accessibility guidance?

**Comment by lee-bunce** [comment]
The extended colour palette could be relevant here:

https://designsystem.gov.scot/styles/colour-customisation/

**Comment by alicebyers5** [comment]
Design system extended colour palette doesn't meet contrast requirements for use in plots. I've been advised design system will be developing guidance for charts in future, at which point we can add SG approved colour palettes to `sgplot`.
