### ISSUE TITLE
Use SG font

### ISSUE THREAD

**Issue by lee-bunce** [DataScienceScotland/sgplot#6]
The SG website uses the Roboto font. Do we want to/can we implement that in the package?

https://designsystem.gov.scot/styles/typography/

**Comment by alicebyers5** [comment]
cRoboto can only be used when working online and in an unrestricted environment. Currently, R tries to install Roboto when the `sgplot` package is loaded. If this is not successful, the built in 'sans' font family will be used. 

The only realistic alternative I can think of would be to include Roboto font files in the package. However, we'd need to consider how to do this whilst adhering to font license. This would also require the font version to be updated routinely.
