### ISSUE TITLE
Improve documentation / develop cookbook?

### ISSUE THREAD

**Issue by lee-bunce** [DataScienceScotland/sgplot#7]
Develop the guidance to include more detailed instruction on how to use it.

The bbplot package for example has a cookbook: https://bbc.github.io/rcookbook/

**Comment by alicebyers5** [comment]
Some ideas:

- Show image of colour palettes
  `scales::show_col(sgplot::sg_colour_values)`
- How to set defaults at top of scripts, e.g.
  `theme_set()`
  `update_geom_defaults()`
- Add examples of charts with functions applied
- Accessibility section to signpost to relevant guidance that should be considered on top of use of `sgplot`.
