### ISSUE TITLE
Ensure sg_theme function implements charts guidance

### ISSUE THREAD

**Issue by lee-bunce** [DataScienceScotland/sgplot#8]
Ensure that the sg_theme function fully implements the recommendations of the [GSS Charts guidance](https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-charts/).

For example:

- Use appropriate font size
- All text should be horizontal
- tick marks
- grid lines
- gaps between bars
- etc.

**Comment by alicebyers5** [comment]
- [ ] Axes and axes labels: #595959
- [ ] Grid lines: #D9D9D9
- [ ] Right align values on y axis
- [ ] Use comma as thousands separator?
- [ ] All text horizontal (if difficult to read, consider different orientation of chart)
- [ ] Categorical data, labels should be **between** tick marks

**Comment by alicebyers5** [comment]
I've done my best to apply as many of the guidance recommendations as possible.

However, I don't think there's a sensible way of controlling the following for all charts:
 
* Size of gap between bars (https://r-graphics.org/recipe-bar-graph-adjust-width)
* Positioning of axis labels between axis ticks (don't think this can be done in ggplot2)
* Use comma as thousands separator in chart labels/text
 
I've added these to the list of considerations in the [accessibility article](https://datasciencescotland.github.io/sgplot/articles/accessibility.html) so they don't get lost/overlooked.

Please reopen this issue if you are reading this and have any ideas!
